# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Final_Project_1(object):
    def setupUi(self, Final_Project_1):
        Final_Project_1.setObjectName("Final_Project_1")
        Final_Project_1.resize(300, 335)
        Final_Project_1.setMinimumSize(QtCore.QSize(300, 335))
        Final_Project_1.setMaximumSize(QtCore.QSize(300, 335))
        self.centralwidget = QtWidgets.QWidget(parent=Final_Project_1)
        self.centralwidget.setObjectName("centralwidget")
        self.vote_jane = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.vote_jane.setGeometry(QtCore.QRect(80, 130, 51, 20))
        self.vote_jane.setObjectName("vote_jane")
        self.voting_group = QtWidgets.QButtonGroup(Final_Project_1)
        self.voting_group.setObjectName("voting_group")
        self.voting_group.addButton(self.vote_jane)
        self.vote_john = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.vote_john.setGeometry(QtCore.QRect(80, 170, 51, 21))
        self.vote_john.setObjectName("vote_john")
        self.voting_group.addButton(self.vote_john)
        self.vote_jacob = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.vote_jacob.setGeometry(QtCore.QRect(160, 130, 61, 21))
        self.vote_jacob.setObjectName("vote_jacob")
        self.voting_group.addButton(self.vote_jacob)
        self.vote_janet = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.vote_janet.setGeometry(QtCore.QRect(160, 170, 51, 21))
        self.vote_janet.setObjectName("vote_janet")
        self.voting_group.addButton(self.vote_janet)
        self.label_pres = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_pres.setGeometry(QtCore.QRect(90, 100, 121, 21))
        self.label_pres.setObjectName("label_pres")
        self.button_vote = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_vote.setGeometry(QtCore.QRect(100, 210, 91, 41))
        self.button_vote.setObjectName("button_vote")
        self.label_check = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_check.setGeometry(QtCore.QRect(60, 260, 191, 21))
        self.label_check.setText("")
        self.label_check.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_check.setObjectName("label_check")
        self.entry_ID = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.entry_ID.setGeometry(QtCore.QRect(140, 70, 113, 20))
        self.entry_ID.setObjectName("entry_ID")
        self.label_ID = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_ID.setGeometry(QtCore.QRect(60, 70, 47, 21))
        self.label_ID.setObjectName("label_ID")
        self.entry_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.entry_name.setGeometry(QtCore.QRect(140, 40, 113, 20))
        self.entry_name.setObjectName("entry_name")
        self.label_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(60, 40, 47, 21))
        self.label_name.setObjectName("label_name")
        self.Label_voting = QtWidgets.QLabel(parent=self.centralwidget)
        self.Label_voting.setGeometry(QtCore.QRect(90, 0, 121, 20))
        self.Label_voting.setBaseSize(QtCore.QSize(5, 5))
        self.Label_voting.setScaledContents(False)
        self.Label_voting.setObjectName("Label_voting")
        Final_Project_1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Final_Project_1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        Final_Project_1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Final_Project_1)
        self.statusbar.setObjectName("statusbar")
        Final_Project_1.setStatusBar(self.statusbar)

        self.retranslateUi(Final_Project_1)
        QtCore.QMetaObject.connectSlotsByName(Final_Project_1)

    def retranslateUi(self, Final_Project_1):
        _translate = QtCore.QCoreApplication.translate
        Final_Project_1.setWindowTitle(_translate("Final_Project_1", "MainWindow"))
        self.vote_jane.setText(_translate("Final_Project_1", "Jane"))
        self.vote_john.setText(_translate("Final_Project_1", "John"))
        self.vote_jacob.setText(_translate("Final_Project_1", "Jacob"))
        self.vote_janet.setText(_translate("Final_Project_1", "Janet"))
        self.label_pres.setText(_translate("Final_Project_1", "Presidential Candidates:"))
        self.button_vote.setText(_translate("Final_Project_1", "SUBMIT VOTE"))
        self.label_ID.setText(_translate("Final_Project_1", "ID"))
        self.label_name.setText(_translate("Final_Project_1", "Name:"))
        self.Label_voting.setText(_translate("Final_Project_1", "VOTING APPLICATION"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Final_Project_1 = QtWidgets.QMainWindow()
    ui = Ui_Final_Project_1()
    ui.setupUi(Final_Project_1)
    Final_Project_1.show()
    sys.exit(app.exec())
